use_frameworks!
platform :ios, '10.0'

source 'git@github.com:zhang232425/ZJSpecs.git'
source 'https://github.com/CocoaPods/Specs.git'

target 'ZJRegion_Example' do
  
  pod 'ZJRegion', :path => '../'

end
